INSERT INTO pais(nombrelargo,nombrecorto,abreviatura,capital) VALUES
("República Argentina","Argentina","ARG","Capital Federal"),
("República Federativa de Brasil","Brasil","BRA","Brasilia"),
("República del Paraguay","Paraguay","PRY","Asunción"),
("República Oriental del Uruguay","Uruguay","URY","Montevideo"),
("República de Cuba","Cuba","CUB","La Habana"),
("Estados Unidos de América","Estados Unidos","USA","Washington D.C."),
("Estados Unidos Mexicanos","México","MEX","Distrito Federal"),
("República de Colombia","Colombia","COL","Bogotá"),
("República del Perú","Perú","PRU","Lima"),
("República del Ecuador","Ecuador","ECU","Quito"),
("República Bolivariana de Venezuela","Venezuela","VEN","Caracas"),
("República de Chile","Chile","CHI","Santiago"),
("Estado Plurinacional de Bolivia","Bolivia","BOL","La Paz"),
("República de Panamá","Panamá","PNM","Panamá"),
("República de Nicaragua","Nicaragua","NIC","Managua"),
("República de Honduras","Honduras","HND","Tegucigalpa"),
("República de Guatemala","Guatemala","GUA","Ciudad de Guatemala"),
("República Dominicana","Rep. Dominicana","DOM","Santo Domingo");